version: '3'
services:
  postgres:
    image: postgres:13.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=testdb
    ports:
      - 5432:5432
    restart: always